### ISSUE TITLE
When connecting wallet connect for the first time console shows error and no balance in wallet menu

### ISSUE THREAD

**Issue by ross-weir** [ross-weir/Donera#91]
```
397-2f601523f21ccba1.js:1 Uncaught (in promise) Error: Sign Client not initialized
    at p.request (397-2f601523f21ccba1.js:1:7356)
    at p.typedRequest (397-2f601523f21ccba1.js:1:7279)
    at requestNodeAPI (397-2f601523f21ccba1.js:1:9301)
    at M (397-2f601523f21ccba1.js:39:54439)
    at C.n.<computed> (397-2f601523f21ccba1.js:39:54799)
    at 397-2f601523f21ccba1.js:39:55053
    at M (397-2f601523f21ccba1.js:39:54439)
    at T.r.<computed> [as getAddressesAddressBalance] (397-2f601523f21ccba1.js:39:55020)
    at 6b87df2e-3be00726c13302d5.js:1:163187
    at 6b87df2e-3be00726c13302d5.js:1:167408
```

refreshing the page fixes the missing balance, probably just need to wait for sign client to init in some way

**Comment by ross-weir** [comment]
actually cant seem to recreate this, it looks like it happened in the `useBalance` hook though

**Comment by ross-weir** [comment]
Get users to test this on testnet to determine if it's really a issue
